//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Busket
    {
        public Busket()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int id_busket { get; set; }
        public Nullable<int> item { get; set; }
        public Nullable<int> number { get; set; }
    
        public virtual Item Item1 { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
    }
}
