//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        public Session()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int id_session { get; set; }
        public int busket { get; set; }
        public Nullable<decimal> sum_prise { get; set; }
    
        public virtual Busket Busket1 { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
    }
}
